package com.ford.exception;

public class ArithmeticClass {
    public int divideNumbers(int dividend, int divisor) throws Exception {
        return dividend / divisor;
//        int k;
//        int[] numbers = new int[1];
//        numbers[0] = 3;
//        try {
//            k = dividend / divisor;
//            k = dividend/numbers[1];
//            System.out.println("in try");
//            return k;
//        } catch (ArrayIndexOutOfBoundsException | ArithmeticException e) {
//            e.printStackTrace();
//            return 0;
//        }
//        finally {
//            System.out.println("welcome");
//        }
    }
}
